### ISSUE TITLE
connect option for using ser2net / socat?

### ISSUE THREAD

**Issue by cicci44** [ndejong/digital-multimeter#4]
been trying out various types of solution. 

client <->wifi/telnet<->ser2net(192.168.1.238:23)<->serial device

**Client side.(windows os)**
create temporary virtual com port(COM8) and point to 192.168.1.238:23 using software **HW Virtual Serial Port** 
start cmd...
`dmm read --connect COM8 --count 0`
it works perfect...

**Client side. (debian)**

```
pi@raspberry:/dev $ sudo socat pty,link=/dev/ttyNET0,waitslave tcp:192.168.1.238:23
pi@raspberry:/dev $ sudo chmod 666 /dev/ttyNET0
pi@raspberry:/dev $ dmm read --connect /dev/ttyNET0 --count 0
```
gets error:
```
/home/pi/.local/lib/python3.9/site-packages/future/standard_library/__init__.py:65: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/home/pi/.local/bin/dmm", line 8, in <module>
    sys.exit(dmm())
  File "/home/pi/.local/lib/python3.9/site-packages/digital_multimeter/cli/entrypoints.py", line 12, in dmm
    click.dmm()
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/digital_multimeter/cli/click.py", line 80, in get_reading
    cli_output(api.get_reading(), format=format, output=output, count=counted)
  File "/home/pi/.local/lib/python3.9/site-packages/digital_multimeter/DigitalMultimeter.py", line 38, in get_reading
    self.__load_multimeter()
  File "/home/pi/.local/lib/python3.9/site-packages/digital_multimeter/DigitalMultimeter.py", line 47, in __load_multimeter
    module = __import__("digital_multimeter.multimeters.{}".format(class_name), fromlist=["digital_multimeter"])
  File "/home/pi/.local/lib/python3.9/site-packages/digital_multimeter/multimeters/MultimeterFortuneFS9721.py", line 5, in <module>
    from serial import SerialException
```
`sudo picocom -b 2400 /dev/ttyNET0`
and i can see i get something unreadable...

**Comment by cicci44** [comment]
i solved it by wipe the rpi, and then i run
```
sudo socat pty,link=/dev/ttyNET0,waitslave tcp:192.168.1.238:23
sudo chmod 666 /dev/ttyNET0
dmm read --connect /dev/ttyUSB8 --count 0
```

**Comment by ndejong** [comment]
@cicci44 thanks for the update - does this close the issue then?
